### PR TITLE
Duration should work when video or audio is missing

### LINKED ISSUE #341: Streaming fails for videos with no audio with 0.17.3 release
Hello, I tried to update videojs-hls but I am hitting a problem with files that do not include audio tracks. I isolated a simple test case that compares the behavior with a working version of videojs-hls (0.11) and the latest one.

Below is a screnshot of the stack trace I see:

screenshot 2015-07-07 17 56 24

### PR DESCRIPTION
**Pull request by dmlap**
If audio or video data is missing for an HLS stream, duration calculations should just use the info that is available. Fixes #341.

### CODE REVIEW

**Comment by gkatsev** [comment]
LGTM

File: test/videojs-hls_test.js [hunk 1]
```diff
@@ -1044,6 +1050,64 @@ test('records the min and max PTS values for a segment', function() {
...
+  tags.push({ pts: 10, bytes: new Uint8Array(1) });
+  standardXHRResponse(requests.pop()); // segment 0
+
+  equal(player.hls.playlists.media().segments[0].minVideoPts, 0, 'recorded min video pts');
+  equal(player.hls.playlists.media().segments[0].maxVideoPts, 10, 'recorded max video pts');
+  strictEqual(player.hls.playlists.media().segments[0].minAudioPts, undefined, 'min audio pts is undefined');
+  strictEqual(player.hls.playlists.media().segments[0].maxAudioPts, undefined, 'max audio pts is undefined');
+});
+
+test('records PTS values for video-only segments', function() {
```
Comment (bclwhitaker) [inline test/videojs-hls_test.js]: audio-only

Comment (dmlap) [inline test/videojs-hls_test.js]: Oops

File: src/playlist.js [hunk 2]
```diff
@@ -91,7 +107,8 @@
     // available PTS information
     for (left = range.start; left < range.end; left++) {
       segment = playlist.segments[left];
-      if (segment.minVideoPts !== undefined) {
+      if (segment.minVideoPts !== undefined ||
```
Comment (FDiskas) [inline src/playlist.js]: Still getting error `TypeError: Cannot read property 'minVideoPts' of undefined`

Comment (dmlap) [inline src/playlist.js]: The entries of a media playlist should be segment objects-- `[undefined]` is not a legal value for that array. Side note: it would be better to file this sort of thing as an issue. Line comments might get overlooked.
