### PR TITLE
Don't append segments that have already been appended

### LINKED ISSUE #430: drainBuffer can be called after updating is set to false
`updateend` is fired asynchronously, so it's possible drainBuffer() will be called after `sourceBuffer.updating` is false but before `this.pendingSegment_` is properly cleared out. This causes the ArrayBuffer to be transferred to the transmuxer twice, which triggers an exception because it is neutered.

### PR DESCRIPTION
**Pull request by dmlap**
Fixes #430. If drainBuffer is called after updating is reset on the sourceBuffer but before updateend fires, a segment could be appended twice. Check to make sure a segment hasn't already been appended before proceeding with draining the buffer.

### CODE REVIEW

File: src/videojs-hls.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ keyFailed = function(key) {
   return key.retries && key.retries >= 2;
 };
 
-videojs.Hls = videojs.extend(Component, {
+videojs.HlsHandler = videojs.extend(Component, {
```
Comment (dmlap) [inline src/videojs-hls.js]: This is the actual rename.

**Comment by saxena-gaurav** [comment]
@dmlap : Changes looks good.

File: src/videojs-hls.js [hunk 2]
```diff
@@ -486,31 +487,32 @@ videojs.Hls.prototype.seekable = function() {
...
-videojs.Hls.prototype.updateDuration = function(playlist) {
+videojs.HlsHandler.prototype.updateDuration = function(playlist) {
   var oldDuration = this.mediaSource.duration,
       newDuration = videojs.Hls.Playlist.duration(playlist),
       setDuration = function() {
         this.mediaSource.duration = newDuration;
         this.tech_.trigger('durationchange');
+
+        // update seekable
+        if (seekable.length !== 0 && newDuration === Infinity) {
```
Comment (imbcmdth) [inline src/videojs-hls.js]: Below we trigger `durationchange` after setting seekable; here we do it before. Since there is no `seekablechange` event, we probably want to trigger `durationchange` afterwards here as well for now.
