### PR TITLE
fix: introduce videojs 6 forward compatibility while maintaining backward compatibilty

### LINKED ISSUE #968: Compatibility with videojs 6.0 RC
## Description
Can't play m3u8 files in video.js 6.0.0-RC.0 but it still play in video.js 5.15.1
The video played and showed "No compatible source was found for this media."

## Steps to reproduce
1. Import media from d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 and other m3u8 files
2. Press play but it show "No compatible source was found for this media."

### Error output
* Press play but it show "No compatible source was found for this media."

### videojs-contrib-hls version
* videojs-contrib-hls 4.1.1

### videojs version
* video.js 6.0.0-RC.0

### Browsers
* Google Chrome version 55.0.2883.87 m (64-bit)

### Platforms
* Windows 10 Pro version 1607 64bit

### PR DESCRIPTION
**Pull request by gkatsev**
This makes it backwards and forwards compatible to videojs 6 and as far back as [5.2](https://github.com/videojs/video.js/blob/master/CHANGELOG.md#520-2015-11-10) when the tech registry was added.

Fix #968

### CODE REVIEW

**Comment by gkatsev** [comment]
Looks like this doesn't fix compat for vjs 6 since `Hls` a regular object is registered as a component which is currently disallowed.

**Comment by BrandonOCasey** [comment]
I'm not sure that registerComponent call is actually needed

**Comment by mjneil** [comment]
If users expect to be able to access hls with `videojs.getComponent('Hls')` then we would lose backwards compatibility with removing the register.

**Comment by gkatsev** [comment]
A potential workaround is to not register `Hls` as a component if we're in a videojs 6 env. For example:
```js
if (!videojs.use) {
  videojs.registerComponent('Hls');
}
```
This keeps compat for 5.x and sets us to remove it from hls when 5.x support is dropped.

**Comment by gkatsev** [comment]
Also, for better or worse, videojs 6.0 no longer checks for components on the `videojs` object, it won't error out/warn in the way that prompted using it in the first place.

**Comment by gkatsev** [comment]
I think this PR could go in without answering the `registerComponent` question.

**Comment by gkatsev** [comment]
And for `plugin`, we could either leave it or we can change it to be something like:
```js
if (videojs.registerPlugin) {
  videojs.registerPlugin(...);
} else {
  videojs.plugin(...);
}
```

**Comment by gkatsev** [comment]
So, I updated the PR:
* use `getTech` instead of `getComponent`
* verify that the flash tech is included before attaching something to it
* if `registerPlugin` is available, use it instead
* if `videojs.use` is available, *don't* register "Hls" as a component
  this isn't too bad since `videojs.Hls` is still around. Plus, that one won't cause any issues since the code that checks for components on the videojs object is removed in videojs 6. Plus, given that this is a videojs project, I don't think it's too bad for it to be attaching itself as `videojs.Hls`.

**Comment by BrandonOCasey** [comment]
@gkatsev you will also have to change `addTrack_` to `addTrack` on vjs6 https://github.com/videojs/videojs-contrib-hls/blob/master/src/master-playlist-controller.js#L217

**Comment by gkatsev** [comment]
It seems to be working just fine for me? Maybe the version of vjs I was testing with is a bit outdated, hm...

**Comment by BrandonOCasey** [comment]
Also a lot of the unit tests are failing on vjs6,

**Comment by gkatsev** [comment]
Saw an issue with evented which should be fixed here: https://github.com/videojs/video.js/pull/3990

**Comment by gkatsev** [comment]
Oh, I had to set the `useCueTags` option. Updated that line.

**Comment by gkatsev** [comment]
I'm looking into the test failures with vjs 6.0. However, those are going to go into a separate PR

**Comment by mjneil** [comment]
LGTM

File: src/master-playlist-controller.js [hunk 1]
```diff
@@ -212,7 +212,6 @@ export class MasterPlaylistController extends videojs.EventTarget {
       this.cueTagsTrack_ = this.tech_.addTextTrack('metadata',
         'ad-cues');
       this.cueTagsTrack_.inBandMetadataTrackDispatchType = '';
-      this.tech_.textTracks().addTrack_(this.cueTagsTrack_);
```
Comment (BrandonOCasey) [inline src/master-playlist-controller.js]: Shouldn't this have just been changed to `this.tech_.textTracks().addTrack(this.cueTagsTrack_);` rather than removed?

Comment (gkatsev) [inline src/master-playlist-controller.js]: The track is added automatically inside of `addTextTrack`.
